# 代替設定：より安定したビルド設定
[phases.setup]
nixPkgs = ['go', 'gcc']

[phases.build]
cmds = [
    'go version',
    'go env',
    'go mod download',
    'go install github.com/swaggo/swag/cmd/swag@latest',
    'export PATH=$PATH:$(go env GOPATH)/bin',
    'swag init',
    'CGO_ENABLED=1 go build -o main .'
]

[phases.start]
cmd = './main'

[variables]
CGO_ENABLED = '1'
GOTOOLCHAIN = 'local'
GOPROXY = 'https://proxy.golang.org,direct' 