[phases.setup]
nixPkgs = ['go_1_21']

[phases.build]
cmds = [
    'go mod download',
    'go install github.com/swaggo/swag/cmd/swag@latest',
    'swag init',
    'go build -o main .'
]

[phases.start]
cmd = './main'

[variables]
CGO_ENABLED = '1'
GOTOOLCHAIN = 'local' 